;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	buffer-menu
	indent-for-tab-command
	kill-region
	menu-bar-open
	paredit-doublequote
	paredit-forward-slurp-sexp
	paredit-splice-sexp
	paredit-wrap-round
	))

(setq mc/cmds-to-run-once
      '(
	helm-M-x
	paredit-forward-delete
	paredit-newline
	yaml-electric-backspace
	))
