;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	buffer-menu
	end-of-buffer
	forward-sentence
	indent-for-tab-command
	keyboard-escape-quit
	kill-region
	menu-bar-open
	paredit-doublequote
	paredit-forward-slurp-sexp
	paredit-open-round
	paredit-splice-sexp
	paredit-wrap-round
	))

(setq mc/cmds-to-run-once
      '(
	cider-eval-defun-at-point
	helm-M-x
	paredit-backward
	paredit-forward-delete
	paredit-newline
	yaml-electric-backspace
	))
